### ISSUE TITLE
Implement .before and .after functions for [http] middleware

### ISSUE THREAD

**Issue by Marak** [bigcompany/resources#46]
In progress

**Comment by Marak** [comment]
see: https://github.com/bigcompany/resources/commit/e34aee551260ca394906d479a5c997ae6ed54463

Should be working now. Waiting for an update from @olalonde for new version of `connectr` with API change.

**Comment by olalonde** [comment]
https://github.com/olalonde/connectr/commit/86dd8119ddc6bfd15b0e50447918ecbae2ca7c62 might solve your problem. I haven't pushed it to npm yet but if you can try it `npm install https://github.com/olalonde/connectr.git` and let me know if it works well. I did a quick test and it seemed to be working as expected. I'll publish on npm if you can confirm it solves your problem.

The syntax is:

``` javascript
app = require('connectr').patch(app);
```

**Comment by Marak** [comment]
@olalonde - looks good

**Comment by olalonde** [comment]
Ok, published to 0.0.4.
