### ISSUE TITLE
Add unit tests for mesh resource

### ISSUE THREAD

**Issue by Marak** [bigcompany/resources#6]
Use https://github.com/bigcompany/resources/tree/master/mesh/example as an API reference.

You'll also want to capture other units which are not covered in the example, but available in the API.

**Comment by jfhbrook** [comment]
Added some tests here: https://github.com/bigcompany/resources/commit/16af56eb8e38212e06583b9ccbe87c98776a02bf

Ran into [an interesting issue with engine.io](https://github.com/LearnBoost/engine.io-client/issues/160) that makes the tests less clean than I'd like, but other than that I think the coverage is reasonable.
